server:
  port: 8083
Spring:
  application:
    name: customer-core
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: test-kafka-cluster
    bootstrap-servers: 127.0.0.1:9095
test:
  topic: test_topic
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


